/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : LED0.C
**     Project   : CF2_0
**     Processor : MCF52255CAF80
**     Beantype  : BitIO
**     Version   : Bean 02.073, Driver 01.01, CPU db: 3.00.000
**     Compiler  : CodeWarrior MCF C Compiler
**     Date/Time : 2012-3-23, 17:47
**     Abstract  :
**         This bean "BitIO" implements an one-bit input/output.
**         It uses one bit/pin of a port.
**         Note: This bean is set to work in Output direction only.
**         Methods of this bean are mostly implemented as a macros
**         (if supported by target language and compiler).
**     Settings  :
**         Used pin                    :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       79            |  FEC_TXD1_PTJ3
**             ----------------------------------------------------
**
**         Port name                   : PORTTJ
**
**         Bit number (in port)        : 3
**         Bit mask of the port        : 0x0008
**
**         Initial direction           : Output (direction cannot be changed)
**         Initial output value        : 1
**         Initial pull option         : up
**
**         Port data register          : PORTTJ    [0x00100006]
**         Port control register       : DDRTJ     [0x0010001E]
**         Port function register      : PTJPAR    [0x00100066]
**
**         Optimization for            : speed
**     Contents  :
**         GetVal - bool LED0_GetVal(void);
**         PutVal - void LED0_PutVal(bool Val);
**         ClrVal - void LED0_ClrVal(void);
**         SetVal - void LED0_SetVal(void);
**         NegVal - void LED0_NegVal(void);
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE LED0. */

#include "LED0.h"
  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"


/*
** ===================================================================
**     Method      :  LED0_GetVal (bean BitIO)
**
**     Description :
**         This method returns an input value.
**           a) direction = Input  : reads the input value from the
**                                   pin and returns it
**           b) direction = Output : returns the last written value
**         Note: This bean is set to work in Output direction only.
**     Parameters  : None
**     Returns     :
**         ---             - Input value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)

** ===================================================================
*/
/*
bool LED0_GetVal(void)

**  This method is implemented as a macro. See LED0.h file.  **
*/

/*
** ===================================================================
**     Method      :  LED0_PutVal (bean BitIO)
**
**     Description :
**         This method writes the new output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Val             - Output value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)
**     Returns     : Nothing
** ===================================================================
*/
void LED0_PutVal(bool Val)
{
  if (Val) {
    setReg8(SETTJ, 0x08);              /* SETTJ3=0x01 */
  } else { /* !Val */
    setReg8(CLRTJ, 0xF7);              /* CLRTJ3=0x00 */
  } /* !Val */
}

/*
** ===================================================================
**     Method      :  LED0_ClrVal (bean BitIO)
**
**     Description :
**         This method clears (sets to zero) the output value.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void LED0_ClrVal(void)

**  This method is implemented as a macro. See LED0.h file.  **
*/

/*
** ===================================================================
**     Method      :  LED0_SetVal (bean BitIO)
**
**     Description :
**         This method sets (sets to one) the output value.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void LED0_SetVal(void)

**  This method is implemented as a macro. See LED0.h file.  **
*/

/*
** ===================================================================
**     Method      :  LED0_NegVal (bean BitIO)
**
**     Description :
**         This method negates (inverts) the output value.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void LED0_NegVal(void)

**  This method is implemented as a macro. See LED0.h file.  **
*/


/* END LED0. */
/*
** ###################################################################
**
**     This file was created by Processor Expert 1.05 [04.27]
**     for the Freescale MCF series of microcontrollers.
**
** ###################################################################
*/
