/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : RightCnt.C
**     Project   : CF2_0
**     Processor : MCF52255CAF80
**     Beantype  : EventCntr16
**     Version   : Bean 02.134, Driver 01.04, CPU db: 3.00.000
**     Compiler  : CodeWarrior MCF C Compiler
**     Date/Time : 2012-3-23, 16:13
**     Abstract  :
**         This bean "EventCntr16" implements an 16-bit event counter.
**         It counts the external events (specified edges of the external
**         signal). It uses a hardware timer counter.
**         The counter width is extended or taperred to 16 bits.
**     Settings  :
**         Timer name                  : DTIM3 [32-bit]
**
**         Counting mode               : Simple counter
**
**         Used input pin              : 
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       13            |  DTIN3_DTOUT3_PWM6_PTC3
**             ----------------------------------------------------
**
**         Initialization:
**              Timer                  : Enabled
**              Events                 : Enabled
**
**         Timer registers
**         Counter register            : DTCN3     [0x04CC]
**         Mode register               : DTCR3     [0x04C8]
**         Run register                : DTCR3     [0x04C8]
**     Contents  :
**         Reset        - byte RightCnt_Reset(void);
**         GetNumEvents - byte RightCnt_GetNumEvents(word *Value);
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE RightCnt. */

#include "RightCnt.h"


volatile static bool Overflow;         /* Internal overflow flag */

/*
** ===================================================================
**     Method      :  RightCnt_Reset (bean EventCntr16)
**
**     Description :
**         This method resets the external event counter (sets it to
**         zero).
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
** ===================================================================
*/
byte RightCnt_Reset(void)
{
  setReg32(DTCN3,0x00);                /* Set counter register */
  Overflow = FALSE;                    /* Clear internal overflow flag */
  return ERR_OK;                       /* Return OK */
}

/*
** ===================================================================
**     Method      :  RightCnt_GetNumEvents (bean EventCntr16)
**
**     Description :
**         This method returns the number of the external events.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Value           - A pointer to the returned number of
**                           the external events
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_OVERFLOW - Timer overflow
** ===================================================================
*/
byte RightCnt_GetNumEvents(word *Value)
{
  *Value = (word)getReg32(DTCN3);      /* Get number of events */
  if (Overflow) {                      /* If an overflow of the counter occured */
    return ERR_OVERFLOW;               /* Return overflow error */
  }
  return ERR_OK;                       /* Return OK */
}

/*
** ===================================================================
**     Method      :  RightCnt_Interrupt (bean EventCntr16)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes event(s) of the bean.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
__declspec(interrupt) void RightCnt_Interrupt(void)
{
  setReg8Bit(DTER3,REF);               /* Clear reference interrupt flag */
  Overflow = TRUE;                     /* Set an internal overflow flag */
}

/*
** ===================================================================
**     Method      :  RightCnt_Init (bean EventCntr16)
**
**     Description :
**         Initializes the associated peripheral(s) and the bean internal 
**         variables. The method is called automatically as a part of the 
**         application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void RightCnt_Init(void)
{
  /* DTMR3: PS=0,CE=0,OM=0,ORRI=0,FRR=0,CLK=0,RST=1 */
  setReg16(DTMR3,0x01);                /* Stop counter module */
  /* DTMR3: PS=0,CE=0,OM=0,ORRI=0,FRR=0,CLK=0,RST=0 */
  setReg16(DTMR3,0x00);                /* Reset counter module */
  /* DTXMR3: DMAEN=0,HALTED=0,??=0,??=0,??=0,??=0,??=0,MODE16=0 */
  setReg8(DTXMR3,0x00);                /* Initialize the timer extended mode register */
  /* DTRR3: REF=0xFFFF */
  setReg32(DTRR3,0xFFFF);              /* Set the reference register */
  /* DTMR3: PS=0,CE=0,OM=0,ORRI=1,FRR=1,CLK=3,RST=1 */
  setReg16(DTMR3,0x1F);                /* Initialize timer mode register */
}
/* END RightCnt. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 1.05 [04.27]
**     for the Freescale MCF series of microcontrollers.
**
** ###################################################################
*/
