/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : RightCnt.H
**     Project   : CF2_0
**     Processor : MCF52255CAF80
**     Beantype  : EventCntr16
**     Version   : Bean 02.134, Driver 01.04, CPU db: 3.00.000
**     Compiler  : CodeWarrior MCF C Compiler
**     Date/Time : 2012-3-23, 16:13
**     Abstract  :
**         This bean "EventCntr16" implements an 16-bit event counter.
**         It counts the external events (specified edges of the external
**         signal). It uses a hardware timer counter.
**         The counter width is extended or taperred to 16 bits.
**     Settings  :
**         Timer name                  : DTIM3 [32-bit]
**
**         Counting mode               : Simple counter
**
**         Used input pin              : 
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       13            |  DTIN3_DTOUT3_PWM6_PTC3
**             ----------------------------------------------------
**
**         Initialization:
**              Timer                  : Enabled
**              Events                 : Enabled
**
**         Timer registers
**         Counter register            : DTCN3     [0x04CC]
**         Mode register               : DTCR3     [0x04C8]
**         Run register                : DTCR3     [0x04C8]
**     Contents  :
**         Reset        - byte RightCnt_Reset(void);
**         GetNumEvents - byte RightCnt_GetNumEvents(word *Value);
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef __RightCnt_H
#define __RightCnt_H

/* MODULE RightCnt. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */

#include "Cpu.h"


#define RightCnt_ENABLE    0x03        /* Value for writing to the CLK bit group to the DTMR3 to enable external events counting */
#define RightCnt_DISABLE   0x00        /* Value for writing to the CLK bit group to the DTMR3 to stop external events counting */


byte RightCnt_Reset(void);
/*
** ===================================================================
**     Method      :  RightCnt_Reset (bean EventCntr16)
**
**     Description :
**         This method resets the external event counter (sets it to
**         zero).
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
** ===================================================================
*/

byte RightCnt_GetNumEvents(word *Value);
/*
** ===================================================================
**     Method      :  RightCnt_GetNumEvents (bean EventCntr16)
**
**     Description :
**         This method returns the number of the external events.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Value           - A pointer to the returned number of
**                           the external events
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_OVERFLOW - Timer overflow
** ===================================================================
*/

void RightCnt_Interrupt(void);
/*
** ===================================================================
**     Method      :  RightCnt_Interrupt (bean EventCntr16)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes event(s) of the bean.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/


void RightCnt_Init(void);
/*
** ===================================================================
**     Method      :  RightCnt_Init (bean EventCntr16)
**
**     Description :
**         Initializes the associated peripheral(s) and the bean internal 
**         variables. The method is called automatically as a part of the 
**         application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

/* END RightCnt. */

#endif
/* ifndef __RightCnt_H */
/*
** ###################################################################
**
**     This file was created by Processor Expert 1.05 [04.27]
**     for the Freescale MCF series of microcontrollers.
**
** ###################################################################
*/
