/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : UART.C
**     Project   : CF2_0
**     Processor : MCF52255CAF80
**     Beantype  : AsynchroSerial
**     Version   : Bean 02.465, Driver 01.02, CPU db: 3.00.000
**     Compiler  : CodeWarrior MCF C Compiler
**     Date/Time : 2012-3-23, 16:13
**     Abstract  :
**         This bean "AsynchroSerial" implements an asynchronous serial
**         communication. The bean supports different settings of
**         parity, word width, stop-bit and communication speed,
**         user can select interrupt or polling handler.
**         Communication speed can be changed also in runtime.
**         The bean requires one on-chip asynchronous serial channel.
**     Settings  :
**         Serial channel              : UART0
**
**         Protocol
**             Init baud rate          : 9600baud
**             Width                   : 8 bits
**             Stop bits               : 1.000
**             Parity                  : none
**             Breaks                  : Disabled
**             Input buffer size       : 0
**             Output buffer size      : 0
**
**         Registers
**             Input buffer            : URB0      [0x020C]
**             Output buffer           : UTB0      [0x020C]
**             Control register        : UMR10     [0x0200]
**             Mode register           : UMR20     [0x0200]
**             Baud setting reg.       : UCSR0     [0x0204]
**
**
**
**         Used pins:
**         ----------------------------------------------------------
**           Function | On package           |    Name
**         ----------------------------------------------------------
**            Input   |     11               |  URXD0_PUA1
**            Output  |     10               |  UTXD0_PUA0
**         ----------------------------------------------------------
**
**
**
**     Contents  :
**         Enable   - byte UART_Enable(void);
**         Disable  - byte UART_Disable(void);
**         RecvChar - byte UART_RecvChar(UART_TComData *Chr);
**         SendChar - byte UART_SendChar(UART_TComData Chr);
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE UART. */

#include "UART.h"


#define OVERRUN_ERR      0x01          /* Overrun error flag bit    */
#define FRAMING_ERR      0x02          /* Framing error flag bit    */
#define PARITY_ERR       0x04          /* Parity error flag bit     */
#define CHAR_IN_RX       0x08          /* Char is in RX buffer      */
#define FULL_TX          0x10          /* Full transmit buffer      */
#define RUNINT_FROM_TX   0x20          /* Interrupt is in progress  */
#define FULL_RX          0x40          /* Full receive buffer       */
#define ENABLED_TX_INT   0x80          /* TX interrupt enabled      */
#define BREAK_ERR        0x0200        /* Break detect              */

static bool EnUser;                    /* Enable/Disable device */
static volatile word SerFlag;          /* Flags for serial communication */
                                       /* Bits: 0 - OverRun error */
                                       /*       1 - Framing error */
                                       /*       2 - Parity error */
                                       /*       3 - Char in RX buffer */
                                       /*       4 - Full TX buffer */
                                       /*       5 - Unused */
                                       /*       6 - Full RX buffer */
                                       /*       7 - TX interrupt enabled */
                                       /*       8 - Unused  */
                                       /*       9 - Break detected  */
                                       /*      10 - Unused */
                                       /*      11 - Unused */
static volatile UART_TComData BufferWrite; /* Output char for serial commmunication */

/*
** ===================================================================
**     Method      :  HWEnDi (bean AsynchroSerial)
**
**     Description :
**         Enables or disables the peripheral(s) associated with the bean.
**         The method is called automatically as a part of the Enable and 
**         Disable methods and several internal methods.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static void HWEnDi(void)
{
  if (EnUser) {                        /* Enable device? */
    setReg8(UCR0, (UCR0_TC0_BITMASK | UCR0_RC0_BITMASK)); /* Enable receiver and transmitter */
    if (SerFlag & FULL_TX) {           /* Is any char in the transmit buffer? */
      while (!testReg8Bit(USR0, TXRDY)){} /* Wait for transmitter empty */
      setReg8(UTB0, BufferWrite);      /* Store char to the transmitter register */
      SerFlag &= ~FULL_TX;             /* Clear the FULL_TX flag */
    }
  } else {
    setReg8(UCR0, (UCR0_TC1_BITMASK | UCR0_RC1_BITMASK)); /* Disable receiver and transmitter */
  }
}

/*
** ===================================================================
**     Method      :  UART_Enable (bean AsynchroSerial)
**
**     Description :
**         Enables the bean - it starts the send and receive
**         functions. Events may be generated
**         ("DisableEvent"/"EnableEvent").
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte UART_Enable(void)
{
  if (!EnUser) {                       /* Is the device disabled by user? */
    EnUser = TRUE;                     /* If yes then set the flag "device enabled" */
    HWEnDi();                          /* Enable the device */
  }
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  UART_Disable (bean AsynchroSerial)
**
**     Description :
**         Disables the bean - it stops the send and receive
**         functions. No events will be generated.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte UART_Disable(void)
{
  if (EnUser) {                        /* Is the device enabled by user? */
    EnUser = FALSE;                    /* If yes then set the flag "device disabled" */
    HWEnDi();                          /* Disable the device */
  }
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  UART_RecvChar (bean AsynchroSerial)
**
**     Description :
**         If any data is received, this method returns one
**         character, otherwise it returns an error code (it does
**         not wait for data). This method is enabled only if the
**         receiver property is enabled.
**         [Note:] Because the preferred method to handle error and
**         break exception in the interrupt mode is to use events
**         <OnError> and <OnBreak> the return value ERR_RXEMPTY has
**         higher priority than other error codes. As a consequence
**         the information about an exception in interrupt mode is
**         returned only if there is a valid character ready to be
**         read.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Chr             - Pointer to a received character
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_RXEMPTY - No data in receiver
**                           ERR_BREAK - Break character is detected
**                           (only when the <Interrupt service>
**                           property is disabled and the <Break
**                           signal> property is enabled)
**                           ERR_COMMON - common error occurred (the
**                           <GetError> method can be used for error
**                           specification)
** ===================================================================
*/
byte UART_RecvChar(UART_TComData *Chr)
{
  register byte Result = ERR_OK;       /* Return error code */
  register word StatReg = getReg8(USR0); /* Read status register */

  setReg8(UCR0, 0x40);                 /* Reset error request flags */
  if (StatReg & (USR0_OE_BITMASK | USR0_FE_BITMASK | USR0_PE_BITMASK | USR0_RB_BITMASK)) { /* Is any error set? */
    Result = ERR_COMMON;               /* If yes then set common error value */
  } else if (!(StatReg & USR0_RXRDY_BITMASK)) { /* Is the reciver empty and no error is set? */
    return ERR_RXEMPTY;                /* If yes then error */
  }
  *Chr = (UART_TComData)getReg8(URB0); /* Read data from the receiver */
  return Result;                       /* Return error code */
}

/*
** ===================================================================
**     Method      :  UART_SendChar (bean AsynchroSerial)
**
**     Description :
**         Sends one character to the channel. If the bean is
**         temporarily disabled (Disable method) SendChar method
**         only stores data into an output buffer. In case of a zero
**         output buffer size, only one character can be stored.
**         Enabling the bean (Enable method) starts the transmission
**         of the stored data. This method is available only if the
**         transmitter property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Chr             - Character to send
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_TXFULL - Transmitter is full
** ===================================================================
*/
byte UART_SendChar(UART_TComData Chr)
{
  if (!testReg8Bit(USR0, TXRDY) || (SerFlag & FULL_TX)) { /* Is the transmitter ready? */
    return ERR_TXFULL;                 /* If yes then error */
  }
  if (EnUser) {                        /* Is device enabled by user? */
    setReg8(UTB0, Chr);                /* Store char to transmitter register */
  } else {
    BufferWrite = Chr;
    SerFlag |= FULL_TX;                /* Set the flag "full TX buffer" */
  }
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  UART_Init (bean AsynchroSerial)
**
**     Description :
**         Initializes the associated peripheral(s) and the bean internal 
**         variables. The method is called automatically as a part of the 
**         application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void UART_Init(void)
{
  SerFlag = 0x00;                      /* Reset flags */
  EnUser = TRUE;                       /* Enable device */
  /* UCR0: ??=0,MISC=3,TC=0,RC=0 */
  setReg8(UCR0, 0x30);                 /* Reset UART transmitter */ 
  /* UCR0: ??=0,MISC=2,TC=0,RC=0 */
  setReg8(UCR0, 0x20);                 /* Reset UART receiver */ 
  /* UMR10: RXRTS=0,RXIRQ=0,ERR=0,PM=2,PT=0,BC=3 */
  setReg8(UMR10, 0x13);                /*  Set the UMR1 register */ 
  /* UMR20: CM=0,TXRTS=0,TXCTS=0,SB=7 */
  setReg8(UMR20, 0x07);                /*  Set the UMR2 register */ 
  /* UCSR0: RCS=0x0D,TCS=0x0D */
  setReg8(UCSR0, 0xDD);                 
  /* UBG10: Divider_MSB=1 */
  setReg8(UBG10, 0x01);                 
  /* UBG20: Divider_LSB=4 */
  setReg8(UBG20, 0x04);                 
  HWEnDi();                            /* Enable/disable device according to status flags */
}


/* END UART. */


/*
** ###################################################################
**
**     This file was created by Processor Expert 1.05 [04.27]
**     for the Freescale MCF series of microcontrollers.
**
** ###################################################################
*/
