/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : Vectors.C
**     Project   : CF2_0
**     Processor : MCF52255CAF80
**     Version   : Bean 01.000, Driver 01.02, CPU db: 3.00.000
**     Compiler  : CodeWarrior MCF C Compiler
**     Date/Time : 2012-3-28, 19:39
**     Abstract  :
**
**     Settings  :
**
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#include "startcf.h"
#include "Cpu.h"
#include "MotorR.h"
#include "MotorL.h"
#include "UART.h"
#include "ADCon.h"
#include "CtrlTimer.h"
#include "LED0.h"
#include "LeftCnt.h"
#include "RightCnt.h"
#include "LeftDir.h"
#include "RightDir.h"
#include "KEY0.h"
#include "KEY1.h"
#include "KEY2.h"
#include "KEY3.h"
#include "Events.h"


/* ISR prototype */
typedef void (*const tIsrFunc)(void);

#pragma define_section vectortable ".vectortable" far_absolute R

static __declspec(vectortable) tIsrFunc _InterruptVectorTable[0xC0] = { /* Interrupt vector table */
  /* ISR name                               No. Address      Lvl Pri Name                       Description */
  (tIsrFunc)__SP_AFTER_RESET,          /* 0x00  0x00000000   -   -   ivINT_INIT_SP              used by PE */
  _startup,                            /* 0x01  0x00000004   -   -   ivINT_INIT_PC              used by PE */
  Cpu_Interrupt,                       /* 0x02  0x00000008   -   -   ivINT_ACC_ERR              unused by PE */
  Cpu_Interrupt,                       /* 0x03  0x0000000C   -   -   ivINT_ADDR_ERR             unused by PE */
  Cpu_Interrupt,                       /* 0x04  0x00000010   -   -   ivINT_ILLEGAL_INSTR        unused by PE */
  Cpu_Interrupt,                       /* 0x05  0x00000014   -   -   ivINT_DIV_ZERO             unused by PE */
  Cpu_Interrupt,                       /* 0x06  0x00000018   -   -   ivReserved6                unused by PE */
  Cpu_Interrupt,                       /* 0x07  0x0000001C   -   -   ivReserved7                unused by PE */
  Cpu_Interrupt,                       /* 0x08  0x00000020   -   -   ivINT_PRIVILEGE_VIOL       unused by PE */
  Cpu_Interrupt,                       /* 0x09  0x00000024   -   -   ivINT_TRACE                unused by PE */
  Cpu_Interrupt,                       /* 0x0A  0x00000028   -   -   ivINT_UNIMPLEMENTED_A_LINE unused by PE */
  Cpu_Interrupt,                       /* 0x0B  0x0000002C   -   -   ivINT_UNIMPLEMENTED_F_LINE unused by PE */
  Cpu_Interrupt,                       /* 0x0C  0x00000030   -   -   ivINT_DEBUG                unused by PE */
  Cpu_Interrupt,                       /* 0x0D  0x00000034   -   -   ivReserved13               unused by PE */
  Cpu_Interrupt,                       /* 0x0E  0x00000038   -   -   ivINT_FORMAT_ERR           unused by PE */
  Cpu_Interrupt,                       /* 0x0F  0x0000003C   -   -   ivReserved15               unused by PE */
  Cpu_Interrupt,                       /* 0x10  0x00000040   -   -   ivReserved16               unused by PE */
  Cpu_Interrupt,                       /* 0x11  0x00000044   -   -   ivReserved17               unused by PE */
  Cpu_Interrupt,                       /* 0x12  0x00000048   -   -   ivReserved18               unused by PE */
  Cpu_Interrupt,                       /* 0x13  0x0000004C   -   -   ivReserved19               unused by PE */
  Cpu_Interrupt,                       /* 0x14  0x00000050   -   -   ivReserved20               unused by PE */
  Cpu_Interrupt,                       /* 0x15  0x00000054   -   -   ivReserved21               unused by PE */
  Cpu_Interrupt,                       /* 0x16  0x00000058   -   -   ivReserved22               unused by PE */
  Cpu_Interrupt,                       /* 0x17  0x0000005C   -   -   ivReserved23               unused by PE */
  Cpu_Interrupt,                       /* 0x18  0x00000060   -   -   ivINT_SPURIOUS_INT         unused by PE */
  Cpu_Interrupt,                       /* 0x19  0x00000064   -   -   ivReserved25               unused by PE */
  Cpu_Interrupt,                       /* 0x1A  0x00000068   -   -   ivReserved26               unused by PE */
  Cpu_Interrupt,                       /* 0x1B  0x0000006C   -   -   ivReserved27               unused by PE */
  Cpu_Interrupt,                       /* 0x1C  0x00000070   -   -   ivReserved28               unused by PE */
  Cpu_Interrupt,                       /* 0x1D  0x00000074   -   -   ivReserved29               unused by PE */
  Cpu_Interrupt,                       /* 0x1E  0x00000078   -   -   ivReserved30               unused by PE */
  Cpu_Interrupt,                       /* 0x1F  0x0000007C   -   -   ivReserved31               unused by PE */
  Cpu_Interrupt,                       /* 0x20  0x00000080   -   -   ivINT_TRAP0                unused by PE */
  Cpu_Interrupt,                       /* 0x21  0x00000084   -   -   ivINT_TRAP1                unused by PE */
  Cpu_Interrupt,                       /* 0x22  0x00000088   -   -   ivINT_TRAP2                unused by PE */
  Cpu_Interrupt,                       /* 0x23  0x0000008C   -   -   ivINT_TRAP3                unused by PE */
  Cpu_Interrupt,                       /* 0x24  0x00000090   -   -   ivINT_TRAP4                unused by PE */
  Cpu_Interrupt,                       /* 0x25  0x00000094   -   -   ivINT_TRAP5                unused by PE */
  Cpu_Interrupt,                       /* 0x26  0x00000098   -   -   ivINT_TRAP6                unused by PE */
  Cpu_Interrupt,                       /* 0x27  0x0000009C   -   -   ivINT_TRAP7                unused by PE */
  Cpu_Interrupt,                       /* 0x28  0x000000A0   -   -   ivINT_TRAP8                unused by PE */
  Cpu_Interrupt,                       /* 0x29  0x000000A4   -   -   ivINT_TRAP9                unused by PE */
  Cpu_Interrupt,                       /* 0x2A  0x000000A8   -   -   ivINT_TRAP10               unused by PE */
  Cpu_Interrupt,                       /* 0x2B  0x000000AC   -   -   ivINT_TRAP11               unused by PE */
  Cpu_Interrupt,                       /* 0x2C  0x000000B0   -   -   ivINT_TRAP12               unused by PE */
  Cpu_Interrupt,                       /* 0x2D  0x000000B4   -   -   ivINT_TRAP13               unused by PE */
  Cpu_Interrupt,                       /* 0x2E  0x000000B8   -   -   ivINT_TRAP14               unused by PE */
  Cpu_Interrupt,                       /* 0x2F  0x000000BC   -   -   ivINT_TRAP15               unused by PE */
  Cpu_Interrupt,                       /* 0x30  0x000000C0   -   -   ivReserved48               unused by PE */
  Cpu_Interrupt,                       /* 0x31  0x000000C4   -   -   ivReserved49               unused by PE */
  Cpu_Interrupt,                       /* 0x32  0x000000C8   -   -   ivReserved50               unused by PE */
  Cpu_Interrupt,                       /* 0x33  0x000000CC   -   -   ivReserved51               unused by PE */
  Cpu_Interrupt,                       /* 0x34  0x000000D0   -   -   ivReserved52               unused by PE */
  Cpu_Interrupt,                       /* 0x35  0x000000D4   -   -   ivReserved53               unused by PE */
  Cpu_Interrupt,                       /* 0x36  0x000000D8   -   -   ivReserved54               unused by PE */
  Cpu_Interrupt,                       /* 0x37  0x000000DC   -   -   ivReserved55               unused by PE */
  Cpu_Interrupt,                       /* 0x38  0x000000E0   -   -   ivReserved56               unused by PE */
  Cpu_Interrupt,                       /* 0x39  0x000000E4   -   -   ivReserved57               unused by PE */
  Cpu_Interrupt,                       /* 0x3A  0x000000E8   -   -   ivReserved58               unused by PE */
  Cpu_Interrupt,                       /* 0x3B  0x000000EC   -   -   ivReserved59               unused by PE */
  Cpu_Interrupt,                       /* 0x3C  0x000000F0   -   -   ivReserved60               unused by PE */
  Cpu_Interrupt,                       /* 0x3D  0x000000F4   -   -   ivReserved61               unused by PE */
  Cpu_Interrupt,                       /* 0x3E  0x000000F8   -   -   ivReserved62               unused by PE */
  Cpu_Interrupt,                       /* 0x3F  0x000000FC   -   -   ivReserved63               unused by PE */
  Cpu_Interrupt,                       /* 0x40  0x00000100   -   -   ivReserved64               unused by PE */
  Cpu_Interrupt,                       /* 0x41  0x00000104   -   -   ivINT_EPORT_EPF1           unused by PE */
  Cpu_Interrupt,                       /* 0x42  0x00000108   -   -   ivINT_EPORT_EPF2           unused by PE */
  Cpu_Interrupt,                       /* 0x43  0x0000010C   -   -   ivINT_EPORT_EPF3           unused by PE */
  Cpu_Interrupt,                       /* 0x44  0x00000110   -   -   ivINT_EPORT_EPF4           unused by PE */
  Cpu_Interrupt,                       /* 0x45  0x00000114   -   -   ivINT_EPORT_EPF5           unused by PE */
  Cpu_Interrupt,                       /* 0x46  0x00000118   -   -   ivINT_EPORT_EPF6           unused by PE */
  Cpu_Interrupt,                       /* 0x47  0x0000011C   -   -   ivINT_EPORT_EPF7           unused by PE */
  Cpu_INT_SCM_SWTIInterrupt,           /* 0x48  0x00000120   0   0   ivINT_SCM_SWTI             used by PE */
  Cpu_Interrupt,                       /* 0x49  0x00000124   -   -   ivINT_DMA0_DONE            unused by PE */
  Cpu_Interrupt,                       /* 0x4A  0x00000128   -   -   ivINT_DMA1_DONE            unused by PE */
  Cpu_Interrupt,                       /* 0x4B  0x0000012C   -   -   ivINT_DMA2_DONE            unused by PE */
  Cpu_Interrupt,                       /* 0x4C  0x00000130   -   -   ivINT_DMA3_DONE            unused by PE */
  Cpu_Interrupt,                       /* 0x4D  0x00000134   -   -   ivINT_UART0                unused by PE */
  Cpu_Interrupt,                       /* 0x4E  0x00000138   -   -   ivINT_UART1                unused by PE */
  Cpu_Interrupt,                       /* 0x4F  0x0000013C   -   -   ivINT_UART2                unused by PE */
  Cpu_Interrupt,                       /* 0x50  0x00000140   -   -   ivReserved80               unused by PE */
  Cpu_Interrupt,                       /* 0x51  0x00000144   -   -   ivINT_I2C0_IIF             unused by PE */
  Cpu_Interrupt,                       /* 0x52  0x00000148   -   -   ivINT_QSPI                 unused by PE */
  Cpu_Interrupt,                       /* 0x53  0x0000014C   -   -   ivINT_DTIM0                unused by PE */
  Cpu_Interrupt,                       /* 0x54  0x00000150   -   -   ivINT_DTIM1                unused by PE */
  LeftCnt_Interrupt,                   /* 0x55  0x00000154   4   3   ivINT_DTIM2                used by PE */
  RightCnt_Interrupt,                  /* 0x56  0x00000158   4   3   ivINT_DTIM3                used by PE */
  Cpu_Interrupt,                       /* 0x57  0x0000015C   -   -   ivINT_FEC_X_INTF           unused by PE */
  Cpu_Interrupt,                       /* 0x58  0x00000160   -   -   ivINT_FEC_X_INTB           unused by PE */
  Cpu_Interrupt,                       /* 0x59  0x00000164   -   -   ivINT_FEC_UN               unused by PE */
  Cpu_Interrupt,                       /* 0x5A  0x00000168   -   -   ivINT_FEC_RL               unused by PE */
  Cpu_Interrupt,                       /* 0x5B  0x0000016C   -   -   ivINT_FEC_R_INTF           unused by PE */
  Cpu_Interrupt,                       /* 0x5C  0x00000170   -   -   ivINT_FEC_R_INTB           unused by PE */
  Cpu_Interrupt,                       /* 0x5D  0x00000174   -   -   ivINT_FEC_MII              unused by PE */
  Cpu_Interrupt,                       /* 0x5E  0x00000178   -   -   ivINT_FEC_LC               unused by PE */
  Cpu_Interrupt,                       /* 0x5F  0x0000017C   -   -   ivINT_FEC_HBERR            unused by PE */
  Cpu_Interrupt,                       /* 0x60  0x00000180   -   -   ivINT_FEC_GRA              unused by PE */
  Cpu_Interrupt,                       /* 0x61  0x00000184   -   -   ivINT_FEC_EBERR            unused by PE */
  Cpu_Interrupt,                       /* 0x62  0x00000188   -   -   ivINT_FEC_BABT             unused by PE */
  Cpu_Interrupt,                       /* 0x63  0x0000018C   -   -   ivINT_FEC_BABR             unused by PE */
  Cpu_Interrupt,                       /* 0x64  0x00000190   -   -   ivReserved100              unused by PE */
  Cpu_Interrupt,                       /* 0x65  0x00000194   -   -   ivReserved101              unused by PE */
  Cpu_Interrupt,                       /* 0x66  0x00000198   -   -   ivReserved102              unused by PE */
  Cpu_Interrupt,                       /* 0x67  0x0000019C   -   -   ivReserved103              unused by PE */
  Cpu_Interrupt,                       /* 0x68  0x000001A0   -   -   ivINT_RNGA                 unused by PE */
  Cpu_Interrupt,                       /* 0x69  0x000001A4   -   -   ivINT_GPT_TOF              unused by PE */
  Cpu_Interrupt,                       /* 0x6A  0x000001A8   -   -   ivINT_GPT_PAIF             unused by PE */
  Cpu_Interrupt,                       /* 0x6B  0x000001AC   -   -   ivINT_GPT_PAOVF            unused by PE */
  Cpu_Interrupt,                       /* 0x6C  0x000001B0   -   -   ivINT_GPT_C0F              unused by PE */
  Cpu_Interrupt,                       /* 0x6D  0x000001B4   -   -   ivINT_GPT_C1F              unused by PE */
  Cpu_Interrupt,                       /* 0x6E  0x000001B8   -   -   ivINT_GPT_C2F              unused by PE */
  Cpu_Interrupt,                       /* 0x6F  0x000001BC   -   -   ivINT_GPT_C3F              unused by PE */
  Cpu_Interrupt,                       /* 0x70  0x000001C0   -   -   ivINT_PMM_LVDF             unused by PE */
  ADCon_InterruptCC,                   /* 0x71  0x000001C4   4   3   ivINT_ADC_ADCA             used by PE */
  Cpu_Interrupt,                       /* 0x72  0x000001C8   -   -   ivINT_ADC_ADCB             unused by PE */
  Cpu_Interrupt,                       /* 0x73  0x000001CC   4   3   ivINT_ADC_ADCINT           unused by PE */
  Cpu_Interrupt,                       /* 0x74  0x000001D0   -   -   ivINT_PWM                  unused by PE */
  Cpu_Interrupt,                       /* 0x75  0x000001D4   -   -   ivINT_USB                  unused by PE */
  Cpu_Interrupt,                       /* 0x76  0x000001D8   -   -   ivReserved118              unused by PE */
  CtrlTimer_Interrupt,                 /* 0x77  0x000001DC   4   3   ivINT_PIT0_PIF             used by PE */
  Cpu_Interrupt,                       /* 0x78  0x000001E0   -   -   ivINT_PIT1_PIF             unused by PE */
  Cpu_Interrupt,                       /* 0x79  0x000001E4   -   -   ivReserved121              unused by PE */
  Cpu_Interrupt,                       /* 0x7A  0x000001E8   -   -   ivINT_CFM_CBEIF            unused by PE */
  Cpu_Interrupt,                       /* 0x7B  0x000001EC   -   -   ivINT_CFM_CCIF             unused by PE */
  Cpu_Interrupt,                       /* 0x7C  0x000001F0   -   -   ivINT_CFM_PVIF             unused by PE */
  Cpu_Interrupt,                       /* 0x7D  0x000001F4   -   -   ivINT_CFM_AEIF             unused by PE */
  Cpu_Interrupt,                       /* 0x7E  0x000001F8   -   -   ivINT_I2C1_IIF             unused by PE */
  Cpu_Interrupt,                       /* 0x7F  0x000001FC   -   -   ivINT_RTC                  unused by PE */
  Cpu_Interrupt,                       /* 0x80  0x00000200   -   -   ivReserved128              unused by PE */
  Cpu_Interrupt,                       /* 0x81  0x00000204   -   -   ivReserved129              unused by PE */
  Cpu_Interrupt,                       /* 0x82  0x00000208   -   -   ivReserved130              unused by PE */
  Cpu_Interrupt,                       /* 0x83  0x0000020C   -   -   ivReserved131              unused by PE */
  Cpu_Interrupt,                       /* 0x84  0x00000210   -   -   ivReserved132              unused by PE */
  Cpu_Interrupt,                       /* 0x85  0x00000214   -   -   ivReserved133              unused by PE */
  Cpu_Interrupt,                       /* 0x86  0x00000218   -   -   ivReserved134              unused by PE */
  Cpu_Interrupt,                       /* 0x87  0x0000021C   -   -   ivReserved135              unused by PE */
  Cpu_Interrupt,                       /* 0x88  0x00000220   -   -   ivINT_FLEXCAN_BUF0I        unused by PE */
  Cpu_Interrupt,                       /* 0x89  0x00000224   -   -   ivINT_FLEXCAN_BUF1I        unused by PE */
  Cpu_Interrupt,                       /* 0x8A  0x00000228   -   -   ivINT_FLEXCAN_BUF2I        unused by PE */
  Cpu_Interrupt,                       /* 0x8B  0x0000022C   -   -   ivINT_FLEXCAN_BUF3I        unused by PE */
  Cpu_Interrupt,                       /* 0x8C  0x00000230   -   -   ivINT_FLEXCAN_BUF4I        unused by PE */
  Cpu_Interrupt,                       /* 0x8D  0x00000234   -   -   ivINT_FLEXCAN_BUF5I        unused by PE */
  Cpu_Interrupt,                       /* 0x8E  0x00000238   -   -   ivINT_FLEXCAN_BUF6I        unused by PE */
  Cpu_Interrupt,                       /* 0x8F  0x0000023C   -   -   ivINT_FLEXCAN_BUF7I        unused by PE */
  Cpu_Interrupt,                       /* 0x90  0x00000240   -   -   ivINT_FLEXCAN_BUF8I        unused by PE */
  Cpu_Interrupt,                       /* 0x91  0x00000244   -   -   ivINT_FLEXCAN_BUF9I        unused by PE */
  Cpu_Interrupt,                       /* 0x92  0x00000248   -   -   ivINT_FLEXCAN_BUF10I       unused by PE */
  Cpu_Interrupt,                       /* 0x93  0x0000024C   -   -   ivINT_FLEXCAN_BUF11I       unused by PE */
  Cpu_Interrupt,                       /* 0x94  0x00000250   -   -   ivINT_FLEXCAN_BUF12I       unused by PE */
  Cpu_Interrupt,                       /* 0x95  0x00000254   -   -   ivINT_FLEXCAN_BUF13I       unused by PE */
  Cpu_Interrupt,                       /* 0x96  0x00000258   -   -   ivINT_FLEXCAN_BUF14I       unused by PE */
  Cpu_Interrupt,                       /* 0x97  0x0000025C   -   -   ivINT_FLEXCAN_BUF15I       unused by PE */
  Cpu_Interrupt,                       /* 0x98  0x00000260   -   -   ivINT_FLEXCAN_ERR_INT      unused by PE */
  Cpu_Interrupt,                       /* 0x99  0x00000264   -   -   ivINT_FLEXCAN_BOFF_INT     unused by PE */
  Cpu_Interrupt,                       /* 0x9A  0x00000268   -   -   ivReserved154              unused by PE */
  Cpu_Interrupt,                       /* 0x9B  0x0000026C   -   -   ivReserved155              unused by PE */
  Cpu_Interrupt,                       /* 0x9C  0x00000270   -   -   ivReserved156              unused by PE */
  Cpu_Interrupt,                       /* 0x9D  0x00000274   -   -   ivReserved157              unused by PE */
  Cpu_Interrupt,                       /* 0x9E  0x00000278   -   -   ivReserved158              unused by PE */
  Cpu_Interrupt,                       /* 0x9F  0x0000027C   -   -   ivReserved159              unused by PE */
  Cpu_Interrupt,                       /* 0xA0  0x00000280   -   -   ivReserved160              unused by PE */
  Cpu_Interrupt,                       /* 0xA1  0x00000284   -   -   ivReserved161              unused by PE */
  Cpu_Interrupt,                       /* 0xA2  0x00000288   -   -   ivReserved162              unused by PE */
  Cpu_Interrupt,                       /* 0xA3  0x0000028C   -   -   ivReserved163              unused by PE */
  Cpu_Interrupt,                       /* 0xA4  0x00000290   -   -   ivReserved164              unused by PE */
  Cpu_Interrupt,                       /* 0xA5  0x00000294   -   -   ivReserved165              unused by PE */
  Cpu_Interrupt,                       /* 0xA6  0x00000298   -   -   ivReserved166              unused by PE */
  Cpu_Interrupt,                       /* 0xA7  0x0000029C   -   -   ivReserved167              unused by PE */
  Cpu_Interrupt,                       /* 0xA8  0x000002A0   -   -   ivReserved168              unused by PE */
  Cpu_Interrupt,                       /* 0xA9  0x000002A4   -   -   ivReserved169              unused by PE */
  Cpu_Interrupt,                       /* 0xAA  0x000002A8   -   -   ivReserved170              unused by PE */
  Cpu_Interrupt,                       /* 0xAB  0x000002AC   -   -   ivReserved171              unused by PE */
  Cpu_Interrupt,                       /* 0xAC  0x000002B0   -   -   ivReserved172              unused by PE */
  Cpu_Interrupt,                       /* 0xAD  0x000002B4   -   -   ivReserved173              unused by PE */
  Cpu_Interrupt,                       /* 0xAE  0x000002B8   -   -   ivReserved174              unused by PE */
  Cpu_Interrupt,                       /* 0xAF  0x000002BC   -   -   ivReserved175              unused by PE */
  Cpu_Interrupt,                       /* 0xB0  0x000002C0   -   -   ivReserved176              unused by PE */
  Cpu_Interrupt,                       /* 0xB1  0x000002C4   -   -   ivReserved177              unused by PE */
  Cpu_Interrupt,                       /* 0xB2  0x000002C8   -   -   ivReserved178              unused by PE */
  Cpu_Interrupt,                       /* 0xB3  0x000002CC   -   -   ivReserved179              unused by PE */
  Cpu_Interrupt,                       /* 0xB4  0x000002D0   -   -   ivReserved180              unused by PE */
  Cpu_Interrupt,                       /* 0xB5  0x000002D4   -   -   ivReserved181              unused by PE */
  Cpu_Interrupt,                       /* 0xB6  0x000002D8   -   -   ivReserved182              unused by PE */
  Cpu_Interrupt,                       /* 0xB7  0x000002DC   -   -   ivReserved183              unused by PE */
  Cpu_Interrupt,                       /* 0xB8  0x000002E0   -   -   ivReserved184              unused by PE */
  Cpu_Interrupt,                       /* 0xB9  0x000002E4   -   -   ivReserved185              unused by PE */
  Cpu_Interrupt,                       /* 0xBA  0x000002E8   -   -   ivReserved186              unused by PE */
  Cpu_Interrupt,                       /* 0xBB  0x000002EC   -   -   ivReserved187              unused by PE */
  Cpu_Interrupt,                       /* 0xBC  0x000002F0   -   -   ivReserved188              unused by PE */
  Cpu_Interrupt,                       /* 0xBD  0x000002F4   -   -   ivReserved189              unused by PE */
  Cpu_Interrupt,                       /* 0xBE  0x000002F8   -   -   ivReserved190              unused by PE */
  Cpu_Interrupt                        /* 0xBF  0x000002FC   -   -   ivReserved191              unused by PE */
};

/* CFM init */

#define CFM_KEY_UPPER   0x00
#define CFM_KEY_LOWER   0x00
#define CFM_CFMPROT     0x00
#define CFM_CFMSACC     0x00
#define CFM_CFMDACC     0x00
#define CFM_CFMSEC      0x00

#pragma define_section cfmconfig ".cfmconfig"  far_absolute R
#pragma explicit_zero_data on

static __declspec(cfmconfig)  unsigned long _cfm[6] = {
  CFM_KEY_UPPER,    /* 0x00000400 */
  CFM_KEY_LOWER,    /* 0x00000404 */
  CFM_CFMPROT,      /* 0x00000408 */
  CFM_CFMSACC,      /* 0x0000040C */
  CFM_CFMDACC,      /* 0x00000410 */
  CFM_CFMSEC        /* 0x00000414 */
};


/*
** ###################################################################
**
**     This file was created by Processor Expert 1.05 [04.27]
**     for the Freescale MCF series of microcontrollers.
**
** ###################################################################
*/
